version: '3.8'
services:
  db:
    container_name: tasks_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=J3rlyynh00
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer